### PR TITLE
updated to support protobuf v2.6.1

### PR DESCRIPTION
**Pull request by snikulov**
Hello, 
I've updated CMakeLists.txt to support latest protobuf version (v2.6.1).
Could you please review and merge?
Thank you.

### CODE REVIEW

**Comment by snikulov** [comment]
@jesperes Could you please take a look?

**Comment by jesperes** [comment]
Sorry for the delay. I will take a look as soon as I can.


tors 14 maj 2015 kl 12:39 skrev Sergei Nikulov <notifications@github.com>:

**Comment by jesperes** [comment]
Merged it now. Looks fine. Sorry for not replying earlier.
/Jesper

mån 14 sep. 2015 kl 21:09 skrev Jesper Eskilson jesper@eskilson.se:

**Comment by snikulov** [comment]
:+1:

**Pull request merged**
